library(devtools)
library(Rcpp)
library(RcppArmadillo)
library(coda)
library(abind)
library(ape)
library(fields)
library(spam)
library(dotCall64)
library(grid)
library(MCMCpack)
library(MASS)
library(mvtnorm)
library(nnet)
library(parallel)
library(phytools)
library(tensorA)
library(caTools)
library(HMSC)
set.seed(1)

setwd("~/Desktop/HMSC_model1") 


load(file = "HMSC_train_IUCN_NA_train.RData")
load(file = "HMSC_testdat_theis.RData")
pred.val.mam <- predict(model.1, newdata = HMSC.th.test)